apiVersion: serving.knative.dev/v1
kind: Function
metadata:
  name: flask-redis-app
spec:
  runtime: python
  build:
    apiVersion: build.knative.dev/v1alpha1
    kind: Build
    metadata:
      name: flask-redis-app-build
    spec:
      source:
        git:
          url: <your_git_repository_url>
      template:
        spec:
          containers:
            - image: python:3.8-slim
              command:
                - /bin/sh
              args:
                - -c
                - |
                  pip install -r requirements.txt
                  python setup.py install
                  cp -r * /workspace/
              env:
                - name: FUNCTION_SOURCE
                  value: "/workspace"
  deployment:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: flask-redis-app-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: flask-redis-app
      template:
        metadata:
          labels:
            app: flask-redis-app
        spec:
          containers:
            - name: flask-redis-app-container
              image: <your_docker_image>
              ports:
                - containerPort: 8080
              env:
                - name: REDIS_HOST
                  value: <your_redis_host>
                - name: REDIS_PORT
                  value: <your_redis_port>
                - name: FLASK_APP
                  value: <your_flask_app>







