apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-deployment
spec:
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: monitor-container
          image: tizianoadv/monitor:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis-service"
      imagePullSecrets:
        - name: monitor-docker-registry